//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by DASSimulationProj.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_DASSimulationPrTYPE         130
#define ID_WINDOW_MANAGER               131
#define IDS_WINDOWS_MANAGER             132
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDB_MAF_PAHSE_1_BK              182
#define IDB_MAF_TERMINATION             183
#define IDB_MAF_PHASE_1_BITMAP          184
#define IDB_MAF_PHASE_2_BITMAP          185
#define IDB_MAF_PHASE_3_BITMAP          186
#define IDB_MAF_PHASE_4_BITMAP          187
#define IDB_MAF_PHASE_5_BITMAP          188
#define IDB_MAF_PHASE_6_BITMAP          189
#define IDB_MAR_PHASE_1_BITMAP          190
#define IDB_MAR_PHASE_2_BITMAP          191
#define IDB_MAR_PHASE_3_BITMAP          192
#define IDB_MAR_PHASE_4_BITMAP          193
#define IDB_MAR_PHASE_5_BITMAP          194
#define IDB_MAR_PHASE_6_BITMAP          195
#define IDB_MAF_MAR_TERMINATION         196
#define IDB_DAS_SYSTEM                  197
#define IDB_MAFMAR_PAHSE_3_BITMAP		198
#define IDB_MAFMAR_PHASE_6_BITMAP		199

#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        210
#define ID_VIEW_APPLOOK_OFF_XP          211
#define ID_VIEW_APPLOOK_WIN_XP          212
#define ID_VIEW_APPLOOK_OFF_2003        213
#define ID_VIEW_APPLOOK_VS_2005         214
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDD_DLG_LEFT_OUTPUT             310
#define IDD_DLG_MAF_REQUEST             311
#define IDD_DLG_INTRODUCE_MAF_MAR       312
#define IDD_DIALOG1                     319
#define IDD_DLG_MAR_REQUEST             319
#define IDD_DLG_MAR_SIMULATE            321
#define IDD_DLG_MAR_PHASE_1             322
#define IDD_DLG_MAR_PHASE_2             323
#define IDD_DLG_MAR_PHASE_3             324
#define IDD_DLG_MAR_PHASE_4             325
#define IDD_DLG_MAR_PHASE_5             326
#define IDD_DLG_MAR_PHASE_6             327
#define IDD_DLG_MAF_PHASE_1             328
#define IDD_DLG_MAF_PHASE_2             329
#define IDD_DIALOG2                     330
#define IDD_DLG_MAF_PHASE_3             330
#define IDD_DLG_MAF_PHASE_4             331
#define IDD_DLG_MAF_PHASE_5             332
#define IDD_DIALOG3                     333
#define IDD_DLG_MAF_PHASE_6             333
#define IDD_DIALOG4                     334
#define IDD_DLG_CREATE_TASK_WITH_USABLE_TIME	334
#define IDD_DIALOG5                     335
#define IDD_DLG_SETTIME_TO_START_TASK   335
#define IDD_DIALOG6                     336
#define IDD_DIALOG7                     337
#define IDD_DLG_MAF_TERMINATION         337
#define IDD_DIALOG8                     338
#define IDD_DLG_MAR_TERMINATION         338
#define IDD_DIALOG9                     339
#define IDD_DLG_INTRODUCE_MODULES		339
#define IDD_DIALOG10                    340
#define IDD_DLG_SETTING_VIEW_TIME       340
#define IDD_DIALOG11                    341
#define IDD_DLG_INTRODUCE_SYSTEM        341
#define IDD_DIALOG12                    342
#define IDD_DLG_MAFMAR_QUERY            342
#define IDD_DLG_MAFMAR_TERMINATION      343
#define IDD_DLG_MAFMAR_PHASE_2          345
#define IDD_DLG_MAFMAR_PHASE_3          346
#define IDD_DIALOG13                    347
#define IDD_DLG_MAFMAR_PHASE_6          347
#define IDD_DLG_UNEXPECTED_MAR_REQ      348
#define IDD_DIALOG14                    349
#define IDD_DLG_UNEXPETECTED_2D_SHOW    349
#define IDD_DLG_RECONFIG_TASK_ITEM      350
#define IDC_BTN_DAS_TASK_QUERY          1000
#define IDC_BTN_MAF_FORWORD             1001
#define IDC_BTN_MAR_DEFORWORD           1002
#define IDC_BTN_DAS_INTRODUCE           1003
#define IDC_BTN_LOGIN                   1004
#define IDC_BTN_REGISTER                1006
#define IDC_BTN_DAS_SETTING             1008
#define IDC_BTN_DAS_LOGOUT              1010
#define IDC_BTN_SHOW_REGISTERDLG        1012
#define IDC_EDIT_REG_EMAIL              1017
#define IDC_LIST_TDRSS_TUT              1019
#define ID_SIMULATE                     1020
#define IDC_LIST_UP_TDRS_USABLE_TIME    1022
#define IDC_MAR_DATEPICKER_START        1024
#define IDC_RADIO1                      1025
#define IDC_MAR_TIMEPICKER_START        1026
#define IDC_MAR_DATEPICKER_END          1028
#define IDC_RADIO2                      1029
#define IDC_MAR_TIMEPICKER_END          1030
#define IDC_MAR_COMBO_SIC               1032
#define IDC_BTN_APPLY_REQUEST           1033
#define IDC_MAR_COMBO_TDRS              1035
#define IDC_LIST_MAR_US_VIS_TABLE       1039
#define IDC_BTN_QUERY_US_TDRS_VISIBLE_TIME 1040
#define IDC_COMBO1                      1041
#define IDC_COMBO_QUERY_SIC             1041
#define IDC_COMBO_SETTING_TIME_VEL      1041
#define IDC_COMBO_MAR_SSC               1041
#define IDC_LIST_MAR_TASK_CTRL          1042
#define IDC_BUTTON1                     1043
#define IDC_BTN_MAR_SERVICE_PLAN_REQ    1043
#define IDC_BTN_SET_SYS_TIME            1043
#define IDC_BTN_SET_SHOW_TIME           1043
#define IDC_BTN_PAUSE_MAF1              1043
#define IDC_BTN_PAUSE_MAF_FLASH         1043
#define IDC_BTN_PAUSE_MAR_FLASH         1043
#define IDC_BTN_MAF2_PAUSE_FLASH        1043
#define IDC_BTN_MAR2_PAUSE_FLASH        1043
#define IDC_BTN_MAF3_PAUSE_FLASH        1043
#define IDC_BTN_MAR3_PAUSE_FLASH        1043
#define IDC_BTN_MAF6_PAUSE_FLASH        1043
#define IDC_BTN_MAR6_PAUSE_FLASH        1043
#define IDC_BTN_DENY_UNEXPECT_MAR       1043
#define IDC_LIST1                       1044
#define IDC_LIST_ALL_TASK               1044
#define IDC_LIST_UNEXPECTED_MAR_TASK    1044
#define IDC_DAFDAR_MODE                 1045
#define IDC_BUTTON4                     1045
#define IDC_BTN_ACCEPT_UNEXPECTED_MAR   1045
#define IDC_RESET_PRIORITY              1046
#define IDC_MAFMAR_PLAN_REQ             1046
#define IDC_BUTTON6                     1047
#define IDC_UNEXPECT_MODE               1047
#define IDC_MAFMAR_DATEPICKER_START     1047
#define IDC_MAFMAR_DATEPICKER_END       1048
#define IDC_MAFMAR_TIMEPICKER_START     1049
#define IDC_COMBO_SERVICE_LEVEL         1050
#define IDC_MAFMAR_TIMEPICKER_END       1050
#define IDC_COM_TASK_TYPE               1051
#define IDC_MAFMAR_COMBO_TDRS           1051
#define IDC_MAFMAR_COMBO_SIC            1052
#define IDC_MAFMAR_EDIT_MAR_SSC         1053
#define IDC_COMBO2                      1054
#define IDC_LIST_MAFMAR_TASK_CTRL       1054
#define IDC_COMBO_MAR_CHANNEL           1055
#define IDC_LIST_MAFMAR_US_VIS_TABLE    1055
#define IDC_COMBO_TDRS_MAR              1056
#define IDC_BTN_PAUSE_MAFMAR_FLASH      1056
#define IDC_BTN_MAFMAR2_PAUSE_FLASH     1057
#define IDC_BTN_MAFMAR3_PAUSE_FLASH     1058
#define IDC_COMBO_TDRS_QUERY            1059
#define IDC_BTN_MAFMAR6_PAUSE_FLASH     1059
#define IDC_COMBO4                      1071
#define IDC_BUTTON2                     1073
#define IDC_BTN_SETTING_TIMES           1073
#define IDC_BTN_SETTING_SIMULATE_TIME_DAS 1073
#define IDC_BTN_MAF_CREATE_UP_TIME      1074
#define IDC_BTN_MAR_CREATE_UP_TIME      1075
#define IDC_RADIO3                      1076
#define IDC_BTN_MAFMAR_CREATE_UP_TIME   1076
#define IDC_RADIO4                      1077
#define IDC_BUTTON3                     1078
#define IDC_BTN_SETTING_TIME_FREQUENCY_DAS 1078
#define IDC_BTN_DAS_SYSTEM              1078
#define IDC_BTN_MAR_PHASE_2_ANALY       1080
#define IDC_EDIT1                       1090
#define IDC_EDIT_TASK_STATUS            1090
#define IDC_EDIT_MAR_SSC                1090
#define IDC_EDIT_MAF_TASK_SSC           1091
#define IDC_COMPANY_URL                 2041
#define IDC_COMBO_SIC                   2043
#define IDC_COMBO_TASK_STATUS           2044
#define IDC_COMBO_TDRS                  2045
#define IDC_DATEPICKER_START            2046
#define IDC_TIMEPICKER_START            2047
#define IDC_DATEPICKER_END              2049
#define IDC_TIMEPICKER_END              2050
#define IDC_LIST_EMPTY_WIN              2051
#define IDC_LIST_TASK                   2054
#define ID_QUERY_TASK                   2055
#define ID_TASK_GRAPH                   2056
#define ID_DAS_MAF                      2057
#define IDC_DATEPICKER_START_SHOWTIME   2060
#define IDC_TIMEPICKER_START_SHOWTIME   2061
#define ID_TASK_GRAPH2                  3056
#define ID_TASK_SIMULATION              3057
#define ID_DAS_MAR                      3058
#define ID_INIT_TASK                    3059
#define IDC_EDIT_WINDOW_START_DATETIME  3060
#define IDC_EDIT_WINDOW_END_DATETIME    3061
#define IDC_DATEPICKER_SERIVCE_START_DATE 3062
#define IDC_DATEPICKER_SERIVCE_END_DATE 3063
#define IDC_DATEPICKER_SERIVCE_START_TIME 3064
#define IDC_DATEPICKER_SERIVCE_END_TIME 3065
#define IDC_EDIT_TDRS                   3066
#define IDC_EDIT_SIC                    3067
#define IDC_EDIT_SSC                    3068
#define IDC_HTML_PAGE                   3069
#define IDC_DATEPICKER_SERIVCE_START_DATE2 3069
#define IDC_BTN_US_VIEW_WND_SIM         3070
#define ID_MAF_PHASE_1                  32782
#define ID_MAF_PHASE_2                  32783
#define ID_MAF_PHASE_3                  32784
#define ID_MAF_PHASE_4                  32785
#define ID_MAF_PHASE_5                  32786
#define ID_MAF_PHASE_6                  32787
#define ID_MAR_PHASE_1                  32789
#define ID_MAR_PHASE_2                  32790
#define ID_MAR_PHASE_3                  32791
#define ID_MAR_PHASE_4                  32792
#define ID_MAR_PHASE_5                  32793
#define ID_MAR_PHASE_6                  32794
#define ID_MAF_SHOWALL                  32795
#define ID_MAR_SHOWALL                  32796
#define ID_32797                        32797
#define ID_SYS_STRUCTRUE                32798
#define IDM_SETTING_SHOWTIME            32799
#define ID_32800                        32800
#define ID_TEST_UP_TIME                 32801
#define ID_32802                        32802
#define ID_32803                        32803
#define ID_SHOW_LEFT_DOCKPANE           32804
#define ID_HIDE_LEFT_DOCKPANE           32805
#define ID_MAF_32806                    32806
#define ID_MAR_32807                    32807
#define ID_MAF_CLOSE_LOOP_PLAY          32808
#define ID_MAR_CLOSE_LOOP_PLAY          32809

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        351
#define _APS_NEXT_COMMAND_VALUE         32810
#define _APS_NEXT_CONTROL_VALUE         1061
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
